CREATE TABLE roles (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(50)
);
INSERT INTO roles (id, name) VALUES (1, 'AAAAAAAAAAAAAAAAAA');
INSERT INTO roles (id, name) VALUES (2, 'BBBBBBBBBBBBBBBBBB');
INSERT INTO roles (id, name) VALUES (3, 'CCCCCCCCCCCCCCCCCC');
INSERT INTO roles (id, name) VALUES (4, 'DDDDDDDDDDDDDDDDDD');
INSERT INTO roles (id, name) VALUES (5, 'EEEEEEEEEEEEEEEEEE');